---
- name: Variables demonstration
  hosts: rhel
  become: false
  gather_facts: false
  vars:
    my_color: purple
  vars_files:
    - my_variables.yml
  tasks:

    - name: Print the value of my_color
      ansible.builtin.debug:
        msg: The value of the variable my_color is {{ my_color }}
