- name: Variables demonstration
  hosts: all
  become: false
  gather_facts: false

  vars:

    my_string: yellow 

  vars_files:
    - my_vars.yml
      
  tasks:

    - name: Ensure fact_controller learns about my vars
      ansible.builtin.set_fact:
        my_string: white
          
    - name: Load variables from more_vars.yml
      ansible.builtin.include_vars:
        file: more_vars.yml

    - name: Print the value of my_string
      vars:
        my_string: red
      ansible.builtin.debug:
        msg: The value of the variable my_string is {{ my_string }}

