- name: Handler demonstration
  hosts: "{{ my_host | default('servera') }}"
  become: true
  gather_facts: true
  force_handlers: true

  tasks:

    - name: Ensure needed content is present
      notify: Ensure server is rebooted
      ansible.builtin.copy:
        content: Restart
        dest: /var/tmp/reboot
    
    - name: Ensure software updated
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Deliberately fail
      ignore_errors: true
      ansible.builtin.fail:

    - name: Execute handlers now without any delay
      ansible.builtin.meta: flush_handlers
    
    - name: Ensure that we can connect to server
      listen: Reboot server
      ansible.builtin.wait_for:
        port: 22
        delay: 5
        timeout: 20 

  handlers:

    - name: Ensure server is rebooted
      ansible.builtin.reboot:

