- name: Create users in the appropriate groups
  hosts: "{{ myhosts | default('servera') }}"
  become: true
  no_log: true

  vars_files:
    - hash_dictionary_vars.yml

  tasks:

    - name: Ensure groups are created
      loop: "{{ mygroups }}"
      ansible.builtin.group:
        name: "{{ item }}"
        state: "{{ mystate | default('present') }}"

    - name: Ensure users are in their appropriate groups
      loop: "{{ lookup('dict', myusers) }}"
      ansible.builtin.user:
        name: "{{ item['key'] }}"
        state: "{{ mystate | default('present') }}"
        groups: "{{ item['value']['groups'] | default(omit) }}"
        password: "{{ item['value']['password'] | password_hash('sha512') }}"
        update_password: on_create
        generate_ssh_key: true
