- name: Create the Beatles users, and give them access to their databases
  hosts: servera
  gather_facts: false
  become: true

  vars_files:
    - nested_vars.yml
    
  tasks:

    - name: Ensure users exist
      loop: "{{ beatles }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: present

    - name: Ensure software is installed
      ansible.builtin.package:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present

    - name: Ensure mariadb is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Ensure Beatles access to their databases
      loop: "{{ beatles | product(category_db) | list }}"
      community.mysql.mysql_user:
        host: localhost
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: "{{ item[0] }}"
        priv: "{{ item[1] }}.*:ALL"
        append_privs: yes
        password: "{{ db_pass }}"
