---
- name: MariaDB server is running
  hosts: database_dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  
  tasks:
    - name: MariaDB packages are installed
      loop: "{{ mariadb_packages }}"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present

    - name: Start MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
