- name: Demonstrate sequence lookup plugin
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

  - name: Ensure sequence is displayed
    loop: "{{ range(24, 42 + 1, 6) }}"
    debug:
      msg: my current sequence number is {{ item }}
