- name: Create users
  hosts: "{{ my_host | default('servera') }}"
  become: true
  gather_facts: false

  vars:

    my_users:
      - fred
      - barney
      - wilma
      - betty

  tasks:

    - name: Ensure users are at expected state
      loop: "{{ my_users }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | default('redhat') | password_hash('sha512') }}"
        update_password: on_create
