---
- name: playbook to replace the content
  hosts: servera.lab.example.com
  
  tasks:
    - name: replace the file content
      ansible.builtin.replace:
        path: /var/testfile
        regexp: "automation tool"
        replace: "orchestration tool"
