---
- name: Using the file module to ensure SELinux file context
  hosts: serverb.lab.example.com
  remote_user: root
  tasks:
    
    - name: SELinux file context is set to defaults
      ansible.builtin.file:
        path: /home/devops/users.txt
        seuser: _default
        serole: _default
        setype: _default
        selevel: _default
